{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "sftpgo.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sftpgo.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "sftpgo.selectorLabels" . | nindent 6 }}
  policyTypes:
    {{- if .Values.networkPolicy.policyTypes }}
    {{- toYaml .Values.networkPolicy.policyTypes | nindent 4 }}
    {{- else }}
    - Ingress
    - Egress
    {{- end }}
  {{- with .Values.networkPolicy.ingress }}
  ingress:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.networkPolicy.egress }}
  egress:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
